from aeclib.core import RoomType
from aeclib.us.common.dimensions import (
    MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    MINIMUM_CEILING_HEIGHT_STANDARD_INCHES,
)

# Mapping of RoomTypes to their standard minimum height thresholds.
# Rooms not listed here default to standard habitable/occupiable height (90").
ROOM_HEIGHT_THRESHOLDS = {
    RoomType.CORRIDOR: MINIMUM_CEILING_HEIGHT_STANDARD_INCHES,
    RoomType.BATHROOM: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    RoomType.KITCHEN: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    RoomType.STORAGE_ROOM: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    RoomType.LAUNDRY_ROOM: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    RoomType.MEZZANINE: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
    RoomType.BELOW_MEZZANINE: MINIMUM_CEILING_HEIGHT_SERVICE_INCHES,
}
